# Generated by Django 5.2.7 on 2025-10-21 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CornfieldInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('disease_class', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('ms', models.FloatField()),
                ('image_rel', models.CharField(max_length=255)),
                ('gps_fix', models.BooleanField(default=False)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('gps_alt', models.FloatField(blank=True, null=True)),
                ('gps_time', models.DateTimeField(blank=True, null=True)),
                ('gps_source', models.CharField(blank=True, max_length=50, null=True)),
                ('env_ok', models.BooleanField(default=True)),
                ('env_time', models.DateTimeField(blank=True, null=True)),
                ('env_port', models.CharField(blank=True, max_length=50, null=True)),
                ('env_source', models.CharField(blank=True, max_length=50, null=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('hum', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('soil', models.FloatField(blank=True, null=True)),
                ('wind', models.FloatField(blank=True, null=True)),
                ('wind_avg', models.FloatField(blank=True, null=True)),
                ('lux', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cornfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='fields.cornfield')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='fields.farmer')),
            ],
        ),
    ]
