# Generated by Django 5.2.7 on 2025-11-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_cornfieldinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornfieldinfo',
            name='fertilizer_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cornfieldinfo',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cornfieldinfo',
            name='treatment_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cornfieldinfo',
            name='water_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
