# Generated by Django 5.2.7 on 2025-11-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_cornfieldinfo_fertilizer_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornfieldinfo',
            name='summary_comment',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
