spring.application.name=sf-backend
spring.data.mongodb.uri=mongodb+srv://nguyenhoailinh:123321@smartfarming.x7q5cs9.mongodb.net/?retryWrites=true&w=majority&appName=SmartFarming
spring.data.mongodb.database=smart_farming