# Generated by Django 5.2.7 on 2025-11-05 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_cornfieldinfo'),
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerfield',
            name='cornfield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_fields', to='fields.cornfield'),
        ),
    ]
